-- MySQL Script generated by MySQL Workbench
-- Tue Jul 30 22:39:33 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema persons
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema persons
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `persons` DEFAULT CHARACTER SET utf8 ;
USE `persons` ;

-- -----------------------------------------------------
-- Table `persons`.`persons`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `persons`.`persons` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(55) NULL,
  `email` VARCHAR(100) NULL,
  `country` VARCHAR(45) NULL,
  `phone` VARCHAR(13) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `persons`.`workstations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `persons`.`workstations` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `workstation` VARCHAR(100) NULL,
  `date_created` DATE NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `persons`.`employees`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `persons`.`employees` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `person` INT NULL,
  `workstation` INT NULL,
  `hires_date` DATE NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `person_fk`
    FOREIGN KEY (`person`)
    REFERENCES `persons`.`persons` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `employee_fk`
    FOREIGN KEY (`workstation`)
    REFERENCES `persons`.`workstations` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
